apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wil-app-ingress
  labels:
    app: wil-app
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: wil-app
          servicePort: 80