apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: will-playground
  labels:
    app: will-playground
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: will-playground-service
          servicePort: 80