---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil-app
  template:
    metadata:
      labels:
        app: wil-app
    spec:
      containers:
        - name: wil-app
          image: "paulbouwer/hello-kubernetes:1.10"
          env:
            - name: MESSAGE
              value: "Hello from App2"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: wil-app
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: tcp
  selector:
    app: wil-app